on: push
name: deploy
jobs:
  build-and-push:
    name: Build y Push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: ${{ github.ref }}
    - name: Enviar a docker
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ github.repository }}
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      HOLA: test
    needs: build-and-push
    steps:
    - uses: actions/checkout@master
    - name: Deploy
      uses: yokawasa/action-setup-kube-tools@v0.4.0
      with:
        kubectl: '1.20.2'
        kustomize: '3.7.0'
    - name: Comandos Kubectl
      id: kubectl
      run: |
        mkdir -p ~/.kube/
        echo $KUBE_CONFIG_DATA | base64 -di > ~/.kube/config
        cd .kustomize
        kustomize edit set image prueba-gha=${{ github.repository }}:${{ github.sha }}
        kustomize build . | kubectl apply -f -
        kubectl -n prueba rollout status deployment/prueba-gha
        URL=`kubectl -n prueba get ngrok -o=custom-columns='DATA:status.url' | tail -n1`
        while [[ $URL != *"ngrok"* ]]; do
        echo "Still not ready" && sleep 5
          URL=`kubectl -n prueba get ngrok -o=custom-columns='DATA:status.url' | tail -n1`
        done
        echo "::set-output name=url::$URL"
    - name: Agregar comentario ngrok
      uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: "Tienes un nuevo pull request! Previsualizacion: ${{ steps.kubectl.outputs.url }}"
    - name: Enviar SMS ngrok
      uses: twilio-labs/actions-sms@v1
      with:
        fromPhoneNumber: '+12563306234'
        toPhoneNumber: '+59891771694'
        message: "Tienes un nuevo pull request! Previsualizacion: ${{ steps.kubectl.outputs.url }}"
      env:
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
        TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
